CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT, 
    PRICE REAL 
);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES 
  ('1','PEN','1','1','PEN 10MM',25),
  ('2','NOTEBOOK','1','1','NOTEBOOK 150 PAGES',34),
  ('3','TEXT BOOK','1','2','NATIONAL CURRICULUM 2025 X 14',84),
  ('4','PENCIL','2','2','GRAPHITE 4B X 10',64),
  ('5','SCALE','2','2','SCALE 16 INCH X 2', 88.96);

SELECT COUNT(PRODUCT_ID) AS Product_Count FROM PRODUCT;

SELECT AVG(PRICE) AS Average_Price FROM PRODUCT;

SELECT SUM(PRICE) AS Total_Price FROM PRODUCT;
