CREATE TABLE IF NOT EXISTS STUDENT22 (
 ROLL_NO TEXT PRIMARY KEY,
 NAME TEXT NOT NULL,
 ADDRESS TEXT,
 PHONE TEXT,
 AGE INTEGER
);

INSERT INTO STUDENT22 (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
 ('1', 'RAM', 'DELHI', '*******', 18),
 ('2', 'RAMESH', 'GURGAN', '*******', 18),
 ('3', 'SUJIT', 'ROHTAK', '*******', 20),
 ('4', 'SURESH', 'DELHI', '*******', 18),
 ('5', 'AMAN', 'ROHTAK', '*******', 20),
 ('6', 'HARSH', 'GURGAN', '*******', 18);

SELECT * FROM STUDENT22;

SELECT * FROM STUDENT22 WHERE AGE = 18 AND ADDRESS = 'DELHI';

SELECT * FROM STUDENT22 WHERE AGE = 18 AND NAME = 'RAM';
  
SELECT * FROM STUDENT22 WHERE NAME = 'RAM' OR AGE = 20;

SELECT * FROM STUDENT22 WHERE NAME = 'RAM' OR NAME = 'SUJIT';

SELECT * FROM STUDENT22 WHERE (AGE = 18 AND NAME = 'RAM') OR NAME = 'RAMESH';
